services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgres_16
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: openpg
      POSTGRES_PASSWORD: openpgpwd
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - odoo_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U openpg -d odoo"]
      interval: 5s
      timeout: 3s
      retries: 12

  odoo:
    build: .
    container_name: odoo_18_2_marin
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/opt/odoo/.local/share/Odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
    depends_on:
      db:
        condition: service_healthy
    networks:
      - odoo_net

volumes:
  db-data:
  odoo-data:

networks:
  odoo_net:
