version: "3.8"

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: postgres_16
    environment:
      POSTGRES_DB: odoo
      POSTGRES_USER: openpg
      POSTGRES_PASSWORD: openpgpwd
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - odoo_net
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "openpg", "-d", "marin182"]
      interval: 5s
      timeout: 3s
      retries: 12

  odoo:
    build: .
    container_name: odoo_18_2_marin
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/opt/odoo/.local/share/Odoo
    environment:
      - POSTGRES_USER=openpg
      - POSTGRES_PASSWORD=openpgpwd
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - odoo_net

volumes:
  db-data:
  odoo-data:

networks:
  odoo_net:
